services:
  - type: web
    name: ai-gateway
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-gateway-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-gateway-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info

databases:
  - name: ai-gateway-db
    databaseName: ai_gateway
    user: ai_gateway_user
    plan: starter
    region: oregon

services:
  - type: redis
    name: ai-gateway-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru