# This file has been replaced by deploy-to-vercel.yml
# Keeping this file for reference but it's no longer used
# 
# The deployment has been migrated from Google Cloud Run to Vercel
# Please use the new workflow: .github/workflows/deploy-to-vercel.yml